pipeline {
    agent any

    triggers {
        pollSCM "H/15 * * * *"
    }

    environment {
        TIMESHEET_KEY = credentials ('timesheet_key')
        TF_VAR_AWS_ACCESS_KEY = credentials ('AWS_ACCESS_KEY')
        TF_VAR_AWS_SECRET_KEY = credentials ('AWS_SECRET_KEY')
    }

    stages {

        stage('Deploy backend infrastructure') {
        steps {
               dir("terraform/backend"){
               sh 'make'
              }
            }
        }

    }
}