pipeline {
   agent any
   tools {nodejs "nodejs"}
   parameters {
        string(defaultValue: 'eebootcamp-timesheet-frontend-server',description: 's3-bucket-name to upload files', name: 's3-bucket')
    }
    stages {
        stage('Build') {
        steps {
               dir("timetrackerfrontend/deployment"){
               sh 'make'
            }
        }
      }

      stage('Deploy'){
      steps{
           withAWS() {
                     s3Upload(file:'build', bucket:"${params.s3-bucket}", path:'timetrackerfrontend/')
                   }
      }
      }
    }
}