pipeline {
   agent any
   parameters {
        stringParam(defaultValue: 'eebootcamp-timesheet-frontend-server', description: 's3-bucket-name to upload files', name: 's3-bucket')
    }
    stages {
        stage('Build') {
        steps {
               dir("timetrackerfrontend"){
               sh 'make'
            }
        }
      }
      steps{
           withAWS() {
                     s3Upload(file:'build', bucket:${params.s3-bucket}, path:'timetrackerfrontend/')
                   }
      }
    }
}