pipeline {
   agent any

    environment {
                AWS_ACCESS_KEY_ID = credentials ('AWS_ACCESS_KEY')
                AWS_SECRET_ACCESS_KEY = credentials ('AWS_SECRET_KEY')
           }

     parameters {
                   string(defaultValue: 'eebootcamp-timesheet-frontend-server',description: 's3-bucket-name to upload files', name: 's3-bucket')
               }

    tools {nodejs "nodejs"}

    stages {
        stage('Build') {
        steps {
               dir("timetrackerfrontend/deployment"){
               sh 'make'
            }
        }
      }

      stage('Deploy'){
      steps{
           withAWS() {
                     s3Upload(file:'timetrackerfrontend/build', bucket:"${params['s3-bucket']}")
                   }
      }
      }
    }
}