pipeline {
   agent any
   tools {nodejs "node"}
    stages {
        stage('Build and Test') {
        steps {
               dir("timetrackerfrontend"){
               sh 'make'
            }
        }
      }
    }
}