pipeline {
   agent any

   tools {nodejs "nodejs"}

   triggers {
           pollSCM "H/15 * * * *"
       }

    stages {
        stage('Build and Test') {
        steps {
               dir("timetrackerfrontend"){
               sh 'make'
            }
        }
      }
    }
}