pipeline {
    agent any

    environment {
        TF_VAR_AWS_ACCESS_KEY = credentials ('AWS_ACCESS_KEY')
        TF_VAR_AWS_SECRET_KEY = credentials ('AWS_SECRET_KEY')
        AWS_ACCESS_KEY = credentials ('AWS_ACCESS_KEY')
        AWS_SECRET_KEY = credentials ('AWS_SECRET_KEY')
    }

    stages {

        stage('Deploy frontend infrastructure') {
        steps {
               dir("terraform/frontend"){
               sh 'make'
              }
            }
        }

    }
}
