pipeline {
    agent any

    triggers {
        pollSCM "H/15 * * * *"
    }

    stages {

        stage('Build and Test') {
        steps {
               dir("timetrackerbackend"){
                sh 'export JAVA_HOME="${tool 'JDK-11'}"'
                sh 'java -version'
                sh 'make test'
              }
            }
        }

    }
}