pipeline {
    agent any

    triggers {
        pollSCM "H/15 * * * *"
    }

    stages {

        stage('Build and Test') {
        steps {
               dir("timetrackerbackend"){
                env.JAVA_HOME="${tool 'JDK-11'}"
                env.PATH="${env.JAVA_HOME}/bin:${env.PATH}"
                sh 'java -version'
                sh 'make test'
              }
            }
        }

    }
}