pipeline {
   agent any

    environment {
           JAVA_HOME="${tool 'JDK-11'}"
       }

    stages {
        stage('Build and Test') {
        steps {
               dir("acceptance-tests"){
               sh 'make'
            }
        }
      }
    }
}