version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - /some/valid/path/to/jenkins:/var/jenkins_home
    environment:
      JENKINS_HOST_HOME: "/some/valid/path/to/jenkins"
    ports:
      - "49001:8080"
