version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - ${JENKINS_PATH}:/var/jenkins_home
    environment:
      JENKINS_HOST_HOME: ${JENKINS_PATH}
    ports:
      - "49001:8080"
